name: Lint GitHub Actions workflow

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**

jobs:
  lint:
    permissions:
      contents: read
    uses: shuymn/github-actions/.github/workflows/gha.yml@417b9296c6693ab840d5bb5600a18581ab877752